### ISSUE TITLE
Busy hang

### ISSUE THREAD

**Issue by jwr** [apa512/clj-rethinkdb#104] opened 2015-10-20 07:36 UTC
I hit another problem while inserting large amounts of data: the main process eventually hangs at close to 400% CPU usage, while RethinkDB stops receiving new data.

This happened after a loop inserted 14432000 records. The total number to be inserted was 24795802.

Records were inserted in batches (vectors) of 1024 at a time.

Unfortunately, I have little to go on, as the main process just continued spinning, there were no exceptions to be seen. I captured a CPU sample using YourKit, which might point someone to the problem.

This is using `[com.apa512/rethinkdb "0.11.0"]`, so it's not the memory leak I reported before

![2015-10-20 at 09 33](https://cloud.githubusercontent.com/assets/38015/10600879/fa402ef8-770d-11e5-9016-25e9da875d5a.png)

**Comment by danielcompton** [comment] 2015-10-20 08:03
Just to check, are you waiting for each result to return before running the next insert?

**Comment by jwr** [comment] 2015-10-20 08:07
Hmm. The real answer is "I don't know" :-)

I just run a loop that builds the insert queries and calls `r/run` on them. The loop is a `doseq`, so I'm not holding onto the results of the inserts.

**Comment by danielcompton** [comment] 2015-10-20 08:12
r/run is blocking, so that should be waiting. I'll take a look tomorrow.

**Comment by jwr** [comment] 2015-10-20 08:18
Also, this is a fairly large table. Before that I was able to insert 1878859 records and 3699819 records into two other tables, so this is not something that happened immediately.

**Comment by danielcompton** [comment] 2015-10-23 22:51
Hey sorry I haven't had a chance to look into this just yet. As a temporary workaround, have you considered using multiple connections? e.g. closing the old connection and creating a new one every 100,000 inserts? Obviously not a great long term solution, but it might help in the short term.

**Comment by jwr** [comment] 2015-10-28 10:55
Thanks, I don't really need a workaround, because this isn't anything urgent — I'm just trying to use clj-rethinkdb for larger things. It works for my smaller application (https://partsbox.io/), but so far seems to break for larger amounts of data.

I'm increasingly worried about the complexity in the driver and the (inevitable) resulting problems.

**Comment by danielcompton** [comment] 2015-10-28 21:20
I'm looking to move all of the connection and results handling to the official Java RethinkDB driver as soon as there is a release of it, which offloads the hard part to them, and lets us just focus on the query language.

**Comment by jwr** [comment] 2015-12-20 09:53
FWIW, I think this is a very good idea. We are a small community for now, so we should keep our code as simple as possible.

**Comment by danielcompton** [comment] 2016-05-15 06:28
Can you try this again? We ran into a similar sounding issue (nothing was running, but no exceptions being thrown). The root cause turned out to be that all of the go threads were blocked waiting on reads from the db. The connection code has been rewritten with manifold which shouldn't suffer from this.

**Comment by jwr** [comment] 2016-05-16 19:42
Of course. I will have to dig up that project and reproduce the problem again, which might take a while, though.

**Comment by jwr** [comment] 2016-05-22 21:33
I retried this with `0.15.23`. I was able to insert 24795801 records successfully with no hangs or any other problems. I'd say the bug can be closed!

I find it slightly alarming that performance drops with time when inserting larger numbers of records — from about 8-10k inserts/s at the beginning down to around 2k inserts/s after 23M records have been inserted (it's for a table with no indexes, and the data is fairly homogeneous). But I strongly suspect it's a RethinkDB issue. It seems to be reading about twice as much data as is being written to disk.

As for clj-rethinkdb,  I noticed that its performance improved since `0.11.0` — I happened to have notes on how long a certain task took and compared them to the current results:

* `0.11.0`: 275s
* `0.15.23`: 193s

This is with a smaller task that doesn't hit RethinkDB's limitations. That's a 30% improvement! Nice!

**Comment by danielcompton** [comment] 2016-05-22 23:25
Great to hear! The degraded performance after lots of inserts is interesting, although there's not really enough info to say whether that's RethinkDB, the driver, or something else entirely. If you felt like it, taking a VisualVM profile over time would be helpful to check if there's a memory leak which is causing excessive GCing.

Thanks for following up!

**Comment by jwr** [comment] 2016-05-31 19:38
I confirmed that the degraded performance is due to RethinkDB and is to be expected: https://github.com/rethinkdb/rethinkdb/issues/5805

**Comment by danielcompton** [comment] 2016-05-31 20:27
Thanks for that, I'll watch that issue with interest.

**Closed** 2016-05-31 20:26 UTC
Labels: bug
